micronaut:
  application:
    name: keyManagerRest
  server:
    port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${SERVER_PORT:50052}
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'